---
name: deploy to s3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci    

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::547194329427:role/github-oicd-template-Role-1L0NPTNZKTP9D
          # role-session-name: MySessionName
          
      - run: npx -y cdk deploy --require-approval never
        working-directory: ./cdk
